.travis.yml
Node 5 is not LTS so it was dropped.
=> Added travis ci support for modern node versions

lib/core.js, test/archiver.js
The current bitmask for files fails on unix for files with special bits set.
=> feat(file): Add support for file special bits on unix

lib/core.js
The Archiver.bulk() call has been deprecated for a while and various answers on SO and other sites still suggest it, so if there are no planned maintenance fixes and updates to that function, everyone (even those who do not read the docs) should be informed that they are using something that is deprecated.
=> Add a `process.emitWarning` for `deprecated`

package.json
This should fix the deprecation warnings:
> npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
> npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
> npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
=> Updated mocha

lib/core.js, test/archiver.js
=> Promise support

lib/core.js
=> work on progress.

examples/progress.js
Here's my attempt at showing some numbers :).
@ctalkington it's weird but I don't get the correct size from `progress.fs.totalBytes`. On the `fixtures` directory the size I compute is `10829` bytes, but `totalBytes` is `6733`. Could you explain where that may come from?
Anyway, to compute progress we should not use `totalBytes` because it's computed asynchronously and would not be accurate (TODO add this to the example).
Please don't merge yet I still want to add some comments.
=> Add progress example

README.md
Added a mention in the `Quick Start` section of the README.md documentation.
=> Issue #269: Add 'end' event documentation

lib/core.js, test/plugins.js
I found a bug with relative symlinks.  The linkname would get confused and resolve to a relative path that included the location of my node.js server, that had nothing to do with the path of the symlink (either the symlink or the location of the file it pointed to).
For instance, I creeated a relative symlink named `thing2` inside the directory `/workspace`.
The symlink points to a file with absolute location of `/workspace/x/y/z/thing`, but the symlink is relative and so uses `x/y/z/thing`
The variables in scope of the changes work out as follows:
```
task.filepath == "/workspace/thing2"
linkpath ==  "x/y/z/thing"
```
BEFORE CHANGE: 
```
path.resolve(linkPath) == "/Users/jesse/dev/gravity/roles/spacegate/files/workspacesync/x/y/z/thing"
path.relative(...) == …
```
=> Fix relative symlink paths

lib/core.js
`Buffer.concat([])` returns an empty buffer all the way down to 0.8.x.
Alternative way would be to just use `Buffer.alloc(0)` and drop support for outdated Node.js versions (`< 4.5.0 || >= 5.0.0 < 5.10.0`).
Refs:
https://nodejs.org/api/deprecations.html#deprecations_dep0005_buffer_constructor
Tracking: https://github.com/nodejs/node/issues/19079
=> Avoid using deprecated Buffer constructor

lib/core.js, package.json
this optimizes node_modules size, reducing the carried node_modules dependencies by about (4.8 megabytes - 32 kilobytes)
Fixes #334
=> switch to specialized lodash.assign npm module

lib/core.js, package-lock.json, test/archiver.js
Hi, 
The archive object may hang if a fs.stats callback with error is the last called for a sequence of files. This could be observed in test case 'should allow continue on stat failing' if there is some race, but is unlikely to occur during the tests. 
So, I added a test case that can reproduce the bug. 
The fix involves the call of _onQueueDrain also for the _stat_queue (like for _queue).
=> fix for a hang with _statQueue

lib/core.js, package-lock.json, package.json
Hi everyone. 
Many thanks for contributor team👏  great job!
When I was working on xlsx-renderer I founded [vulnerability with async->loadash](https://snyk.io/test/github/siemienik/xlsx-renderer#SNYK-JS-LODASH-567746): 
**It's able to resolve by upgrading `async` to version 3+ what I've just done.**
I hope this will be helpful for many.
FIXES: https://github.com/archiverjs/node-archiver/issues/419, https://github.com/exceljs/exceljs/issues/1250, https://github.com/Siemienik/xlsx-renderer/issues/24 
---
p.s. each star for my fledgeling [xlsx-renderer](https://github.com/Siemienik/xlsx-renderer) library makes a lot of motivation to develop 🥰
=> Resolve vulnerability by updating async to 3.2.0 version

benchmark/simple/pack-zip.js, lib/core.js, package-lock.json, package.json
As described in the following issue: https://github.com/archiverjs/node-archiver/issues/422, [node-glob](https://github.com/isaacs/node-glob) is not designed to handle a huge amount of files: it requires a quantify of memory that is proportional to the number of matched files.
*Why ?* Because, it lists only the folders that appears in the pattern, and it has to memorise all the found files to ensure a same file is not emitted twice.
It makes sense to proceed like this when the pattern matches only a little proportion of the filesystem.
But as it's not a common use case when creating an archive, it would be more efficient to list all the files, and then check if they match the given pattern.
**Advantage**: 
- memory consumptions is fixed, no matter the number of matched files
- it's faster …
=> Replaced glob with readdir-glob to be memory efficient

package.json
since its a security issue we can force it to atleast the most secure version known right now
=> force bump tar-stream from 2.1.2 to 2.1.4

lib/core.js
*node-archiver* doesn't use *node-glob*.
=> Fix glob() `options` parameter's link

README.md, index.js, test/archiver.js
Adding a check if the format is already registered. It useful, if you are using the method `registerFormat() `explicitly, to avoid the error _**"..format already registered",**_ you can check if the format exists using `isRegisteredFormat(format)`, if not, you can register the new one.
Related to the  following issue #461
=> add isRegisteredFormat method

lib/core.js, test/archiver.js
I recently opened these PRs:
https://github.com/archiverjs/node-archiver/pull/468
https://github.com/archiverjs/node-zip-stream/pull/68
But I had a rethink and I think this is a better approach. It just exposes the mode as an optional argument to `symlink`. Setting the mode to `493` for directory symlinks does exactly what I need, and also allows other users to control the permissions however they want.
=> add mode parameter to symlink

lib/core.js
In case of error, the promise should be rejected rather than returning the `this` object. The problem is discussed in detail here 👉  https://github.com/archiverjs/node-archiver/issues/344.
=> Finalize should always return a promise

website/docs/archiver_api.md
In addition to the options supported by `node-readdir-glob`, `archiver` supports an additional `cwd` option that was only documented in example code in the quick start. This PR adds it to the API reference.
=> Add glob method's options.cwd to API docs
